const authTypes = {
  SIGN_IN_REQUEST: 'auth/SIGN_IN_REQUEST',
  SIGN_IN_SUCCESS: 'auth/SIGN_IN_SUCCESS',
  SIGN_IN_ERROR: 'auth/SIGN_IN_ERROR',
  SIGN_UP_REQUEST: 'auth/SIGN_UP_REQUEST',
  SIGN_UP_SUCCESS: 'auth/SIGN_UP_SUCCESS',
  SIGN_UP_ERROR: 'auth/SIGN_UP_ERROR',
  SIGN_OUT: 'auth/SIGN_OUT'
}

export default authTypes;