export const listsTypes = {
  FETCH_LISTS_REQUEST: "lists/FETCH_LISTS_REQUEST",
  FETCH_LISTS_SUCCESS: "lists/FETCH_LISTS_SUCCESS",
  FETCH_LISTS_ERROR: "lists/FETCH_LISTS_ERROR",
  DELETE_LIST_REQUEST: "lists/DELETE_LIST_REQUEST",
  DELETE_LIST_SUCCESS: "lists/DELETE_LIST_SUCCESS",
  DELETE_LIST_ERROR: "lists/DELETE_LIST_ERROR",
};
