export const ActionType = {
  FETCH_LISTS_REQUEST: "FETCH_LISTS_REQUEST",
  FETCH_LISTS_SUCCESS: "FETCH_LISTS_SUCCESS",
  FETCH_LISTS_ERROR: "FETCH_LISTS_ERROR",
  DELETE_LIST_REQUEST: "DELETE_LIST_REQUEST",
  DELETE_LIST_SUCCESS: "DELETE_LIST_SUCCESS",
  DELETE_LIST_ERROR: "DELETE_LIST_ERROR",
};
