export const categoriesTypes = {
  GET_CATEGORIES_REQUEST: "categories/GET_CATEGORIES_REQUEST",
  GET_CATEGORIES_SUCCESS: "categories/GET_CATEGORIES_SUCCESS",
  GET_CATEGORIES_ERROR: "categories/GET_CATEGORIES_ERROR",
  CREATE_CATEGORY_REQUEST: "categories/CREATE_CATEGORY_REQUEST",
  CREATE_CATEGORY_SUCCESS: "categories/CREATE_CATEGORY_SUCCESS",
  CREATE_CATEGORY_ERROR: "categories/CREATE_CATEGORY_ERROR",
  DELETE_CATEGORY_REQUEST: "categories/DELETE_CATEGORY_REQUEST",
  DELETE_CATEGORY_SUCCESS: "categories/DELETE_CATEGORY_SUCCESS",
  DELETE_CATEGORY_ERROR: "categories/DELETE_CATEGORY_ERROR",
};
