export const categoriesTypes = {
  FETCH_CATEGORIES_REQUEST: "categories/FETCH_CATEGORIES_REQUEST",
  FETCH_CATEGORIES_SUCCESS: "categories/FETCH_CATEGORIES_SUCCESS",
  FETCH_CATEGORIES_ERROR: "categories/FETCH_CATEGORIES_ERROR",
  DELETE_CATEGORY_REQUEST: "categories/DELETE_CATEGORY_REQUEST",
  DELETE_CATEGORY_SUCCESS: "categories/DELETE_CATEGORY_SUCCESS",
  DELETE_CATEGORY_ERROR: "categories/DELETE_CATEGORY_ERROR",
};
